### ISSUE TITLE
 AttributeError: 'str' object has no attribute '__context__' error after launching tests with allure

### ISSUE THREAD

**Issue by AlexeyYurchuk** [allure-framework/allure-nose#10]
After i launch my tests via nose and get first failure (in my case assertion error 500 status code instead of 200), i've got attribute error. Here's the log:

[Step 2/2] Status code - 500
[18:29:25][Step 2/2] .Traceback (most recent call last):
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/case.py", line 134, in run
[18:29:25][Step 2/2]     self.runTest(result)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/case.py", line 152, in runTest
[18:29:25][Step 2/2]     test(result)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 625, in **call**
[18:29:25][Step 2/2]     return self.run(_args, *_kwds)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 585, in run
[18:29:25][Step 2/2]     self._feedErrorsToResult(result, outcome.errors)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 516, in _feedErrorsToResult
[18:29:25][Step 2/2]     result.addFailure(test, exc_info)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/proxy.py", line 146, in addFailure
[18:29:25][Step 2/2]     plugins.addFailure(self.test, err)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in __call__
[18:29:25][Step 2/2]     return self.call(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/plugins/manager.py", line 167, in simple
[18:29:25][Step 2/2]     result = meth(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose_allure/**init**.py", line 26, in wrapper
[18:29:25][Step 2/2]     return func(self, _args, *_kwargs)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose_allure/**init**.py", line 134, in addFailure
[18:29:25][Step 2/2]     message, trace = self._parse_tb(err)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose_allure/__init__.py", line 152, in _parse_tb
[18:29:25][Step 2/2]     trace = ''.join(traceback.format_exception(*trace)).strip()
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 181, in format_exception
[18:29:25][Step 2/2]     return list(_format_exception_iter(etype, value, tb, limit, chain))
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 146, in _format_exception_iter
[18:29:25][Step 2/2]     for value, tb in values:
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 125, in _iter_chain
[18:29:25][Step 2/2]     context = exc.__context__
[18:29:25][Step 2/2] AttributeError: 'str' object has no attribute '**context**'
[18:29:25][Step 2/2] 
[18:29:25][Step 2/2] During handling of the above exception, another exception occurred:
[18:29:25][Step 2/2] 
[18:29:25][Step 2/2] Traceback (most recent call last):
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/bin/nosetests", line 11, in <module>
[18:29:25][Step 2/2]     sys.exit(run_exit())
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/core.py", line 121, in **init**
[18:29:25][Step 2/2]     *_extra_args)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/main.py", line 93, in **init**
[18:29:25][Step 2/2]     self.runTests()
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/core.py", line 207, in runTests
[18:29:25][Step 2/2]     result = self.testRunner.run(self.test)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/core.py", line 62, in run
[18:29:25][Step 2/2]     test(result)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 178, in **call**
[18:29:25][Step 2/2]     return self.run(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 225, in run
[18:29:25][Step 2/2]     test(orig)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 178, in **call**
[18:29:25][Step 2/2]     return self.run(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 225, in run
[18:29:25][Step 2/2]     test(orig)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 178, in **call**
[18:29:25][Step 2/2]     return self.run(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 225, in run
[18:29:25][Step 2/2]     test(orig)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 178, in **call**
[18:29:25][Step 2/2]     return self.run(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/suite.py", line 225, in run
[18:29:25][Step 2/2]     test(orig)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/case.py", line 46, in **call**
[18:29:25][Step 2/2]     return self.run(_arg, *_kwarg)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/case.py", line 139, in run
[18:29:25][Step 2/2]     result.addError(self, err)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/proxy.py", line 131, in addError
[18:29:25][Step 2/2]     plugins.addError(self.test, err)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in **call**
[18:29:25][Step 2/2]     return self.call(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/plugins/manager.py", line 167, in simple
[18:29:25][Step 2/2]     result = meth(_arg, *_kw)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose_allure/**init**.py", line 26, in wrapper
[18:29:25][Step 2/2]     return func(self, *args, *_kwargs)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose_allure/**init**.py", line 129, in addError
[18:29:25][Step 2/2]     message, trace = self._parse_tb(err)
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose_allure/__init__.py", line 152, in _parse_tb
[18:29:25][Step 2/2]     trace = ''.join(traceback.format_exception(*trace)).strip()
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 181, in format_exception
[18:29:25][Step 2/2]     return list(_format_exception_iter(etype, value, tb, limit, chain))
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 146, in _format_exception_iter
[18:29:25][Step 2/2]     for value, tb in values:
[18:29:25][Step 2/2]   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 125, in _iter_chain
[18:29:25][Step 2/2]     context = exc.__context__
[18:29:25][Step 2/2] AttributeError: 'str' object has no attribute '**context**'
[18:29:25][Step 2/2] Process exited with code 1

**Comment by sergeychipiga** [comment]
@AlexeyYurchuk thank you for your report. I will devote a time to this problem in the nearest weekend.

**Comment by AlexeyYurchuk** [comment]
Thanks!

**Comment by AlexeyYurchuk** [comment]
@sergeychipiga Hello again, did you have a time to look at the issue yet?
Thanks.

**Comment by Aljutor** [comment]
@sergeychipiga I felt in the same problem

**Comment by schipiga** [comment]
@Aljutor , currently I don't support this project as it is out of scope of my interest. But as it is open source any interested person can fix and send pull-request.

**Comment by dshuga** [comment]
I believe this fixes the issue: https://github.com/allure-framework/allure-nose/pull/27

This was creating a problem for some local tests and I was able to confirm that the change fixed the problem for me.
